### ISSUE TITLE
Cannot find 'code' command

### ISSUE THREAD

**Issue by happyHeartJ** [pr0g/switch-corresponding#7]
Sorry,could you tell me how to install 'code'?

I hit F1 and typed 'install code', but there is not 'code' command.

Could you do me a favor?

**Comment by pr0g** [comment]
Hey!

The 'code' command you're referring to is one you run from command line/terminal. In order to get that to work you need to install code to your system PATH. 

To do this, hit F1 inside of VSCode and type 'install', you should then see an option for 'Shell Command: Install 'code' command in PATH'. If you hit enter to do this, then close VSCode and launch command line/terminal and navigate to the directory you want to work in (e.g. cd path/to/project) and then type 'code .' there, VSCode will open with that directory as your workspace root, and the extension should then work!

Hope that helps!

**Comment by happyHeartJ** [comment]
Thanks, I understand what you mean. And another question, are "extension.switch_corresponding " and "extension.switch_corresponding_same_dir" set in setting.json? how to co bind the key like "alt + O"?

Sorry, I am rookie on vscode.

**Comment by pr0g** [comment]
Hey!

In keybindings.json you should be just able to add another command for that like so...

{ "key": "alt+shift+o",                 "command": "extension.switch_corresponding_same_dir",
                                                   "when": "editorTextFocus" }

So I have alt+o for "extension.switch_corresponding" and alt+shift+o for "extension.switch_corresponding_same_dir" - I think that should work!

Give that a try! :)

**Comment by happyHeartJ** [comment]
OK, I got it! Thank you very very much! Your extension is great!

**Comment by pr0g** [comment]
No problem! :) Thank you!
